package hu.infokristaly.archiwar.back.domain;

// Generated 2012.09.26. 11:18:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import hu.infokristaly.archiwar.front.annotations.EntityInfo;

/**
 * Usergroup generated by hbm2java
 */
@Entity
@Table(name = "usergroup", schema = "public")
public class Usergroup implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -1631677817438656535L;
    private Long id;
    @EntityInfo(info="User group", weight=1, required=true, editor="txt")
    private String usergroup;

    public Usergroup() {
    }

    public Usergroup(String usergroup) {
        this.usergroup = usergroup;
    }

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "usergroupid", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "usergroup", length = 50)
    public String getUsergroup() {
        return this.usergroup;
    }

    public void setUsergroup(String usergroup) {
        this.usergroup = usergroup;
    }

}
